name: Docker Image CI and Push to Hub

on:
  push:
    branches: [ docker-ci ]

jobs:
  docker:
    if: contains(fromJson('["wenh06", "DeepPSP"]'), github.repository_owner)
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: no-test.Dockerfile
          push: true
          tags: wenh06/cinc2022:latest
