name: Docker Image CI and Test

on:
  push:
    branches: [ docker-test ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    if: contains(fromJson('["wenh06", "DeepPSP"]'), github.repository_owner)

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image and run test script
      run: docker build . --file Dockerfile --tag deeppsp-cinc2022-docker-image:$(date +%s)
