name: Docker Image CI and Test

on:
  push:
    branches: [ docker-test ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Docker image and run test script
      run: docker build . --file Dockerfile --tag deeppsp-cinc2022-docker-image:$(date +%s)
